	<footer class="footer d-print-none">
		<div class="container-fluid">
			<div class="d-flex justify-content-between align-items-end">
				<span></span>
				<span></span>
				<span class="text-muted">
					<span class="fs-5 "> &copy; </span>
					<span><?= (new DateTime())->format("Y") ?> <a href="<?= $conf ["AUTHOR_url"] ?>" target="_blank"><?= $conf ["AUTHOR_name"] ?></a></span>
				</span>
			</div>
		</div>
	</footer>

	<div id="dialog-confirm" class="d-none" title="Confirmation">
		<p>
			<span class="ui-icon ui-icon-alert" style="float: left; margin: 12px 12px 20px 0;"></span>
			Ëtes-vous sûr(e) ?
		</p>
	</div>
	