	<header class="d-print-none">
		<!-- Fixed navbar -->
		<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
			<div class="container-fluid">
			
				<a class="navbar-brand" href="<?= $BASE . $f3->alias("homepage") ?>"><?= $f3->get("conf.APP_ICON") ?> <?= $f3->get("conf.APP_NAME") ?></a>
				
				<button class="navbar-toggler" type="button"
					data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
					aria-controls="navbarCollapse" aria-expanded="false"
					aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				
				<div class="collapse navbar-collapse" id="navbarCollapse">
					<ul class="navbar-nav me-auto mb-2 mb-md-0">
						<?php
						foreach ($page["breadcrumbs"] as $i => $breadcrumb)
						{
							$classes = "";
							if ($i === array_key_last($page["breadcrumbs"]))
							{
								$classes = "active "; // disabled
							}
							?>
							<li class="nav-item"><a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"> / </a></li>
							<li class="nav-item"><a class="nav-link <?= $classes ?>" aria-current="page" href="<?= $breadcrumb->getLink() ?>"><?= $breadcrumb->getLabel() ?></a></li>
							<?php
						}
						?>
					</ul>
					
					<!--
					<ul class="navbar-nav me-auto mb-2 mb-md-0">
						<li class="nav-item"><a class="nav-link" href="#" tabindex="-1" aria-disabled="true">menu</a></li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
							data-bs-toggle="dropdown" aria-expanded="false"> Dropdown </a>
							<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
								<li><a class="dropdown-item" href="#">Action</a></li>
								<li><a class="dropdown-item" href="#">Another action</a></li>
								<li><hr class="dropdown-divider"></li>
								<li><a class="dropdown-item" href="#">Something else here</a></li>
							</ul>
						</li>
					</ul>

					<form class="d-flex">
						<input class="form-control me-2" type="search" placeholder="Search"
							aria-label="Search">
						<button class="btn btn-lg btn-outline-success" type="submit">Search</button>
					</form>
					 -->
				</div>
			</div>
		</nav>
	</header>
	