<?php
use Lib\Matrix;
?>

	<!-- Begin page content -->
	<main role="main" class="container-fluid">

		<h1><?= $page["title"] ?></h1>
		
		<?php
		Matrix::display_html_table ($data);
		
		array_shift($data); // remove headers
		foreach ($data as $coach) {
			?>
			<a href="<?= $f3->get("BASE") . $f3->alias("coachChange", ["id" => $coach ["id"]]) ?>">changer <?= $coach ["id"] ?></a> <br/>
			<?php
		}
		?>
		
	</main>
	