	<!-- Begin page content -->
	<main role="main" class="container-fluid">

		<h1><?= $page["title"] ?></h1>
		
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("team") ?>"> team </a></h2>
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("league") ?>"> league </a></h2>
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("transferts") ?>"> transferts </a></h2>
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("coaches") ?>"> coaches </a></h2>
		
	</main>
	