		<h1><?= $page["title"] ?></h1>
		
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("homepage") ?>"> homepage </a></h2>
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("login") ?>"> login </a></h2>
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("logout") ?>"> logout </a></h2>
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("test") ?>"> test </a></h2>
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("data") ?>"> data </a></h2>
		<h2 class="mt-2"><a href="<?= $BASE . $f3->alias("db") ?>"> db test </a></h2>
		
	</main>
	